// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/compiler/plugin.proto

package google.protobuf.compiler;

public final class Plugin {
  private Plugin() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CodeGeneratorRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated string file_to_generate = 1;
    java.util.List<String> getFileToGenerateList();
    int getFileToGenerateCount();
    String getFileToGenerate(int index);
    
    // optional string parameter = 2;
    boolean hasParameter();
    String getParameter();
    
    // repeated .google.protobuf.FileDescriptorProto proto_file = 15;
    java.util.List<com.google.protobuf.DescriptorProtos.FileDescriptorProto> 
        getProtoFileList();
    com.google.protobuf.DescriptorProtos.FileDescriptorProto getProtoFile(int index);
    int getProtoFileCount();
    java.util.List<? extends com.google.protobuf.DescriptorProtos.FileDescriptorProtoOrBuilder> 
        getProtoFileOrBuilderList();
    com.google.protobuf.DescriptorProtos.FileDescriptorProtoOrBuilder getProtoFileOrBuilder(
            int index);
  }
  public static final class CodeGeneratorRequest extends
      com.google.protobuf.GeneratedMessage
      implements CodeGeneratorRequestOrBuilder {
    // Use CodeGeneratorRequest.newBuilder() to construct.
    private CodeGeneratorRequest(Builder builder) {
      super(builder);
    }
    private CodeGeneratorRequest(boolean noInit) {}
    
    private static final CodeGeneratorRequest defaultInstance;
    public static CodeGeneratorRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public CodeGeneratorRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return google.protobuf.compiler.Plugin.internal_static_google_protobuf_compiler_CodeGeneratorRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return google.protobuf.compiler.Plugin.internal_static_google_protobuf_compiler_CodeGeneratorRequest_fieldAccessorTable;
    }
    
    private int bitField0_;
    // repeated string file_to_generate = 1;
    public static final int FILE_TO_GENERATE_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList fileToGenerate_;
    public java.util.List<String>
        getFileToGenerateList() {
      return fileToGenerate_;
    }
    public int getFileToGenerateCount() {
      return fileToGenerate_.size();
    }
    public String getFileToGenerate(int index) {
      return fileToGenerate_.get(index);
    }
    
    // optional string parameter = 2;
    public static final int PARAMETER_FIELD_NUMBER = 2;
    private Object parameter_;
    public boolean hasParameter() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getParameter() {
      Object ref = parameter_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          parameter_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getParameterBytes() {
      Object ref = parameter_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        parameter_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .google.protobuf.FileDescriptorProto proto_file = 15;
    public static final int PROTO_FILE_FIELD_NUMBER = 15;
    private java.util.List<com.google.protobuf.DescriptorProtos.FileDescriptorProto> protoFile_;
    public java.util.List<com.google.protobuf.DescriptorProtos.FileDescriptorProto> getProtoFileList() {
      return protoFile_;
    }
    public java.util.List<? extends com.google.protobuf.DescriptorProtos.FileDescriptorProtoOrBuilder> 
        getProtoFileOrBuilderList() {
      return protoFile_;
    }
    public int getProtoFileCount() {
      return protoFile_.size();
    }
    public com.google.protobuf.DescriptorProtos.FileDescriptorProto getProtoFile(int index) {
      return protoFile_.get(index);
    }
    public com.google.protobuf.DescriptorProtos.FileDescriptorProtoOrBuilder getProtoFileOrBuilder(
        int index) {
      return protoFile_.get(index);
    }
    
    private void initFields() {
      fileToGenerate_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      parameter_ = "";
      protoFile_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getProtoFileCount(); i++) {
        if (!getProtoFile(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < fileToGenerate_.size(); i++) {
        output.writeBytes(1, fileToGenerate_.getByteString(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(2, getParameterBytes());
      }
      for (int i = 0; i < protoFile_.size(); i++) {
        output.writeMessage(15, protoFile_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < fileToGenerate_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(fileToGenerate_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getFileToGenerateList().size();
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getParameterBytes());
      }
      for (int i = 0; i < protoFile_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(15, protoFile_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static google.protobuf.compiler.Plugin.CodeGeneratorRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static google.protobuf.compiler.Plugin.CodeGeneratorRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static google.protobuf.compiler.Plugin.CodeGeneratorRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static google.protobuf.compiler.Plugin.CodeGeneratorRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static google.protobuf.compiler.Plugin.CodeGeneratorRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static google.protobuf.compiler.Plugin.CodeGeneratorRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static google.protobuf.compiler.Plugin.CodeGeneratorRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static google.protobuf.compiler.Plugin.CodeGeneratorRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static google.protobuf.compiler.Plugin.CodeGeneratorRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static google.protobuf.compiler.Plugin.CodeGeneratorRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(google.protobuf.compiler.Plugin.CodeGeneratorRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements google.protobuf.compiler.Plugin.CodeGeneratorRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return google.protobuf.compiler.Plugin.internal_static_google_protobuf_compiler_CodeGeneratorRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return google.protobuf.compiler.Plugin.internal_static_google_protobuf_compiler_CodeGeneratorRequest_fieldAccessorTable;
      }
      
      // Construct using google.protobuf.compiler.Plugin.CodeGeneratorRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getProtoFileFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        fileToGenerate_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        parameter_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (protoFileBuilder_ == null) {
          protoFile_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          protoFileBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return google.protobuf.compiler.Plugin.CodeGeneratorRequest.getDescriptor();
      }
      
      public google.protobuf.compiler.Plugin.CodeGeneratorRequest getDefaultInstanceForType() {
        return google.protobuf.compiler.Plugin.CodeGeneratorRequest.getDefaultInstance();
      }
      
      public google.protobuf.compiler.Plugin.CodeGeneratorRequest build() {
        google.protobuf.compiler.Plugin.CodeGeneratorRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private google.protobuf.compiler.Plugin.CodeGeneratorRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        google.protobuf.compiler.Plugin.CodeGeneratorRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public google.protobuf.compiler.Plugin.CodeGeneratorRequest buildPartial() {
        google.protobuf.compiler.Plugin.CodeGeneratorRequest result = new google.protobuf.compiler.Plugin.CodeGeneratorRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          fileToGenerate_ = new com.google.protobuf.UnmodifiableLazyStringList(
              fileToGenerate_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.fileToGenerate_ = fileToGenerate_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.parameter_ = parameter_;
        if (protoFileBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            protoFile_ = java.util.Collections.unmodifiableList(protoFile_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.protoFile_ = protoFile_;
        } else {
          result.protoFile_ = protoFileBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof google.protobuf.compiler.Plugin.CodeGeneratorRequest) {
          return mergeFrom((google.protobuf.compiler.Plugin.CodeGeneratorRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(google.protobuf.compiler.Plugin.CodeGeneratorRequest other) {
        if (other == google.protobuf.compiler.Plugin.CodeGeneratorRequest.getDefaultInstance()) return this;
        if (!other.fileToGenerate_.isEmpty()) {
          if (fileToGenerate_.isEmpty()) {
            fileToGenerate_ = other.fileToGenerate_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureFileToGenerateIsMutable();
            fileToGenerate_.addAll(other.fileToGenerate_);
          }
          onChanged();
        }
        if (other.hasParameter()) {
          setParameter(other.getParameter());
        }
        if (protoFileBuilder_ == null) {
          if (!other.protoFile_.isEmpty()) {
            if (protoFile_.isEmpty()) {
              protoFile_ = other.protoFile_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureProtoFileIsMutable();
              protoFile_.addAll(other.protoFile_);
            }
            onChanged();
          }
        } else {
          if (!other.protoFile_.isEmpty()) {
            if (protoFileBuilder_.isEmpty()) {
              protoFileBuilder_.dispose();
              protoFileBuilder_ = null;
              protoFile_ = other.protoFile_;
              bitField0_ = (bitField0_ & ~0x00000004);
              protoFileBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getProtoFileFieldBuilder() : null;
            } else {
              protoFileBuilder_.addAllMessages(other.protoFile_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getProtoFileCount(); i++) {
          if (!getProtoFile(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              ensureFileToGenerateIsMutable();
              fileToGenerate_.add(input.readBytes());
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              parameter_ = input.readBytes();
              break;
            }
            case 122: {
              com.google.protobuf.DescriptorProtos.FileDescriptorProto.Builder subBuilder = com.google.protobuf.DescriptorProtos.FileDescriptorProto.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addProtoFile(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated string file_to_generate = 1;
      private com.google.protobuf.LazyStringList fileToGenerate_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureFileToGenerateIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          fileToGenerate_ = new com.google.protobuf.LazyStringArrayList(fileToGenerate_);
          bitField0_ |= 0x00000001;
         }
      }
      public java.util.List<String>
          getFileToGenerateList() {
        return java.util.Collections.unmodifiableList(fileToGenerate_);
      }
      public int getFileToGenerateCount() {
        return fileToGenerate_.size();
      }
      public String getFileToGenerate(int index) {
        return fileToGenerate_.get(index);
      }
      public Builder setFileToGenerate(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFileToGenerateIsMutable();
        fileToGenerate_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addFileToGenerate(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureFileToGenerateIsMutable();
        fileToGenerate_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllFileToGenerate(
          Iterable<String> values) {
        ensureFileToGenerateIsMutable();
        super.addAll(values, fileToGenerate_);
        onChanged();
        return this;
      }
      public Builder clearFileToGenerate() {
        fileToGenerate_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      void addFileToGenerate(com.google.protobuf.ByteString value) {
        ensureFileToGenerateIsMutable();
        fileToGenerate_.add(value);
        onChanged();
      }
      
      // optional string parameter = 2;
      private Object parameter_ = "";
      public boolean hasParameter() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getParameter() {
        Object ref = parameter_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          parameter_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setParameter(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        parameter_ = value;
        onChanged();
        return this;
      }
      public Builder clearParameter() {
        bitField0_ = (bitField0_ & ~0x00000002);
        parameter_ = getDefaultInstance().getParameter();
        onChanged();
        return this;
      }
      void setParameter(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        parameter_ = value;
        onChanged();
      }
      
      // repeated .google.protobuf.FileDescriptorProto proto_file = 15;
      private java.util.List<com.google.protobuf.DescriptorProtos.FileDescriptorProto> protoFile_ =
        java.util.Collections.emptyList();
      private void ensureProtoFileIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          protoFile_ = new java.util.ArrayList<com.google.protobuf.DescriptorProtos.FileDescriptorProto>(protoFile_);
          bitField0_ |= 0x00000004;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          com.google.protobuf.DescriptorProtos.FileDescriptorProto, com.google.protobuf.DescriptorProtos.FileDescriptorProto.Builder, com.google.protobuf.DescriptorProtos.FileDescriptorProtoOrBuilder> protoFileBuilder_;
      
      public java.util.List<com.google.protobuf.DescriptorProtos.FileDescriptorProto> getProtoFileList() {
        if (protoFileBuilder_ == null) {
          return java.util.Collections.unmodifiableList(protoFile_);
        } else {
          return protoFileBuilder_.getMessageList();
        }
      }
      public int getProtoFileCount() {
        if (protoFileBuilder_ == null) {
          return protoFile_.size();
        } else {
          return protoFileBuilder_.getCount();
        }
      }
      public com.google.protobuf.DescriptorProtos.FileDescriptorProto getProtoFile(int index) {
        if (protoFileBuilder_ == null) {
          return protoFile_.get(index);
        } else {
          return protoFileBuilder_.getMessage(index);
        }
      }
      public Builder setProtoFile(
          int index, com.google.protobuf.DescriptorProtos.FileDescriptorProto value) {
        if (protoFileBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProtoFileIsMutable();
          protoFile_.set(index, value);
          onChanged();
        } else {
          protoFileBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setProtoFile(
          int index, com.google.protobuf.DescriptorProtos.FileDescriptorProto.Builder builderForValue) {
        if (protoFileBuilder_ == null) {
          ensureProtoFileIsMutable();
          protoFile_.set(index, builderForValue.build());
          onChanged();
        } else {
          protoFileBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addProtoFile(com.google.protobuf.DescriptorProtos.FileDescriptorProto value) {
        if (protoFileBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProtoFileIsMutable();
          protoFile_.add(value);
          onChanged();
        } else {
          protoFileBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addProtoFile(
          int index, com.google.protobuf.DescriptorProtos.FileDescriptorProto value) {
        if (protoFileBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProtoFileIsMutable();
          protoFile_.add(index, value);
          onChanged();
        } else {
          protoFileBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addProtoFile(
          com.google.protobuf.DescriptorProtos.FileDescriptorProto.Builder builderForValue) {
        if (protoFileBuilder_ == null) {
          ensureProtoFileIsMutable();
          protoFile_.add(builderForValue.build());
          onChanged();
        } else {
          protoFileBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addProtoFile(
          int index, com.google.protobuf.DescriptorProtos.FileDescriptorProto.Builder builderForValue) {
        if (protoFileBuilder_ == null) {
          ensureProtoFileIsMutable();
          protoFile_.add(index, builderForValue.build());
          onChanged();
        } else {
          protoFileBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllProtoFile(
          Iterable<? extends com.google.protobuf.DescriptorProtos.FileDescriptorProto> values) {
        if (protoFileBuilder_ == null) {
          ensureProtoFileIsMutable();
          super.addAll(values, protoFile_);
          onChanged();
        } else {
          protoFileBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearProtoFile() {
        if (protoFileBuilder_ == null) {
          protoFile_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          protoFileBuilder_.clear();
        }
        return this;
      }
      public Builder removeProtoFile(int index) {
        if (protoFileBuilder_ == null) {
          ensureProtoFileIsMutable();
          protoFile_.remove(index);
          onChanged();
        } else {
          protoFileBuilder_.remove(index);
        }
        return this;
      }
      public com.google.protobuf.DescriptorProtos.FileDescriptorProto.Builder getProtoFileBuilder(
          int index) {
        return getProtoFileFieldBuilder().getBuilder(index);
      }
      public com.google.protobuf.DescriptorProtos.FileDescriptorProtoOrBuilder getProtoFileOrBuilder(
          int index) {
        if (protoFileBuilder_ == null) {
          return protoFile_.get(index);  } else {
          return protoFileBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends com.google.protobuf.DescriptorProtos.FileDescriptorProtoOrBuilder> 
           getProtoFileOrBuilderList() {
        if (protoFileBuilder_ != null) {
          return protoFileBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(protoFile_);
        }
      }
      public com.google.protobuf.DescriptorProtos.FileDescriptorProto.Builder addProtoFileBuilder() {
        return getProtoFileFieldBuilder().addBuilder(
            com.google.protobuf.DescriptorProtos.FileDescriptorProto.getDefaultInstance());
      }
      public com.google.protobuf.DescriptorProtos.FileDescriptorProto.Builder addProtoFileBuilder(
          int index) {
        return getProtoFileFieldBuilder().addBuilder(
            index, com.google.protobuf.DescriptorProtos.FileDescriptorProto.getDefaultInstance());
      }
      public java.util.List<com.google.protobuf.DescriptorProtos.FileDescriptorProto.Builder> 
           getProtoFileBuilderList() {
        return getProtoFileFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.google.protobuf.DescriptorProtos.FileDescriptorProto, com.google.protobuf.DescriptorProtos.FileDescriptorProto.Builder, com.google.protobuf.DescriptorProtos.FileDescriptorProtoOrBuilder> 
          getProtoFileFieldBuilder() {
        if (protoFileBuilder_ == null) {
          protoFileBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.google.protobuf.DescriptorProtos.FileDescriptorProto, com.google.protobuf.DescriptorProtos.FileDescriptorProto.Builder, com.google.protobuf.DescriptorProtos.FileDescriptorProtoOrBuilder>(
                  protoFile_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          protoFile_ = null;
        }
        return protoFileBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:google.protobuf.compiler.CodeGeneratorRequest)
    }
    
    static {
      defaultInstance = new CodeGeneratorRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:google.protobuf.compiler.CodeGeneratorRequest)
  }
  
  public interface CodeGeneratorResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string error = 1;
    boolean hasError();
    String getError();
    
    // repeated .google.protobuf.compiler.CodeGeneratorResponse.File file = 15;
    java.util.List<google.protobuf.compiler.Plugin.CodeGeneratorResponse.File> 
        getFileList();
    google.protobuf.compiler.Plugin.CodeGeneratorResponse.File getFile(int index);
    int getFileCount();
    java.util.List<? extends google.protobuf.compiler.Plugin.CodeGeneratorResponse.FileOrBuilder> 
        getFileOrBuilderList();
    google.protobuf.compiler.Plugin.CodeGeneratorResponse.FileOrBuilder getFileOrBuilder(
            int index);
  }
  public static final class CodeGeneratorResponse extends
      com.google.protobuf.GeneratedMessage
      implements CodeGeneratorResponseOrBuilder {
    // Use CodeGeneratorResponse.newBuilder() to construct.
    private CodeGeneratorResponse(Builder builder) {
      super(builder);
    }
    private CodeGeneratorResponse(boolean noInit) {}
    
    private static final CodeGeneratorResponse defaultInstance;
    public static CodeGeneratorResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public CodeGeneratorResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return google.protobuf.compiler.Plugin.internal_static_google_protobuf_compiler_CodeGeneratorResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return google.protobuf.compiler.Plugin.internal_static_google_protobuf_compiler_CodeGeneratorResponse_fieldAccessorTable;
    }
    
    public interface FileOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // optional string name = 1;
      boolean hasName();
      String getName();
      
      // optional string insertion_point = 2;
      boolean hasInsertionPoint();
      String getInsertionPoint();
      
      // optional string content = 15;
      boolean hasContent();
      String getContent();
    }
    public static final class File extends
        com.google.protobuf.GeneratedMessage
        implements FileOrBuilder {
      // Use File.newBuilder() to construct.
      private File(Builder builder) {
        super(builder);
      }
      private File(boolean noInit) {}
      
      private static final File defaultInstance;
      public static File getDefaultInstance() {
        return defaultInstance;
      }
      
      public File getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return google.protobuf.compiler.Plugin.internal_static_google_protobuf_compiler_CodeGeneratorResponse_File_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return google.protobuf.compiler.Plugin.internal_static_google_protobuf_compiler_CodeGeneratorResponse_File_fieldAccessorTable;
      }
      
      private int bitField0_;
      // optional string name = 1;
      public static final int NAME_FIELD_NUMBER = 1;
      private Object name_;
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getName() {
        Object ref = name_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            name_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      // optional string insertion_point = 2;
      public static final int INSERTION_POINT_FIELD_NUMBER = 2;
      private Object insertionPoint_;
      public boolean hasInsertionPoint() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getInsertionPoint() {
        Object ref = insertionPoint_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            insertionPoint_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getInsertionPointBytes() {
        Object ref = insertionPoint_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          insertionPoint_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      // optional string content = 15;
      public static final int CONTENT_FIELD_NUMBER = 15;
      private Object content_;
      public boolean hasContent() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getContent() {
        Object ref = content_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            content_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getContentBytes() {
        Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      private void initFields() {
        name_ = "";
        insertionPoint_ = "";
        content_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getInsertionPointBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBytes(15, getContentBytes());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getInsertionPointBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(15, getContentBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @Override
      protected Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static google.protobuf.compiler.Plugin.CodeGeneratorResponse.File parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static google.protobuf.compiler.Plugin.CodeGeneratorResponse.File parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static google.protobuf.compiler.Plugin.CodeGeneratorResponse.File parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static google.protobuf.compiler.Plugin.CodeGeneratorResponse.File parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static google.protobuf.compiler.Plugin.CodeGeneratorResponse.File parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static google.protobuf.compiler.Plugin.CodeGeneratorResponse.File parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static google.protobuf.compiler.Plugin.CodeGeneratorResponse.File parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static google.protobuf.compiler.Plugin.CodeGeneratorResponse.File parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static google.protobuf.compiler.Plugin.CodeGeneratorResponse.File parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static google.protobuf.compiler.Plugin.CodeGeneratorResponse.File parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(google.protobuf.compiler.Plugin.CodeGeneratorResponse.File prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements google.protobuf.compiler.Plugin.CodeGeneratorResponse.FileOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return google.protobuf.compiler.Plugin.internal_static_google_protobuf_compiler_CodeGeneratorResponse_File_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return google.protobuf.compiler.Plugin.internal_static_google_protobuf_compiler_CodeGeneratorResponse_File_fieldAccessorTable;
        }
        
        // Construct using google.protobuf.compiler.Plugin.CodeGeneratorResponse.File.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          name_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          insertionPoint_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          content_ = "";
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return google.protobuf.compiler.Plugin.CodeGeneratorResponse.File.getDescriptor();
        }
        
        public google.protobuf.compiler.Plugin.CodeGeneratorResponse.File getDefaultInstanceForType() {
          return google.protobuf.compiler.Plugin.CodeGeneratorResponse.File.getDefaultInstance();
        }
        
        public google.protobuf.compiler.Plugin.CodeGeneratorResponse.File build() {
          google.protobuf.compiler.Plugin.CodeGeneratorResponse.File result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private google.protobuf.compiler.Plugin.CodeGeneratorResponse.File buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          google.protobuf.compiler.Plugin.CodeGeneratorResponse.File result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public google.protobuf.compiler.Plugin.CodeGeneratorResponse.File buildPartial() {
          google.protobuf.compiler.Plugin.CodeGeneratorResponse.File result = new google.protobuf.compiler.Plugin.CodeGeneratorResponse.File(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.name_ = name_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.insertionPoint_ = insertionPoint_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.content_ = content_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof google.protobuf.compiler.Plugin.CodeGeneratorResponse.File) {
            return mergeFrom((google.protobuf.compiler.Plugin.CodeGeneratorResponse.File)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(google.protobuf.compiler.Plugin.CodeGeneratorResponse.File other) {
          if (other == google.protobuf.compiler.Plugin.CodeGeneratorResponse.File.getDefaultInstance()) return this;
          if (other.hasName()) {
            setName(other.getName());
          }
          if (other.hasInsertionPoint()) {
            setInsertionPoint(other.getInsertionPoint());
          }
          if (other.hasContent()) {
            setContent(other.getContent());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                name_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                insertionPoint_ = input.readBytes();
                break;
              }
              case 122: {
                bitField0_ |= 0x00000004;
                content_ = input.readBytes();
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // optional string name = 1;
        private Object name_ = "";
        public boolean hasName() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public String getName() {
          Object ref = name_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setName(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          name_ = value;
          onChanged();
          return this;
        }
        public Builder clearName() {
          bitField0_ = (bitField0_ & ~0x00000001);
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        void setName(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000001;
          name_ = value;
          onChanged();
        }
        
        // optional string insertion_point = 2;
        private Object insertionPoint_ = "";
        public boolean hasInsertionPoint() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public String getInsertionPoint() {
          Object ref = insertionPoint_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            insertionPoint_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setInsertionPoint(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          insertionPoint_ = value;
          onChanged();
          return this;
        }
        public Builder clearInsertionPoint() {
          bitField0_ = (bitField0_ & ~0x00000002);
          insertionPoint_ = getDefaultInstance().getInsertionPoint();
          onChanged();
          return this;
        }
        void setInsertionPoint(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000002;
          insertionPoint_ = value;
          onChanged();
        }
        
        // optional string content = 15;
        private Object content_ = "";
        public boolean hasContent() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        public String getContent() {
          Object ref = content_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            content_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setContent(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          content_ = value;
          onChanged();
          return this;
        }
        public Builder clearContent() {
          bitField0_ = (bitField0_ & ~0x00000004);
          content_ = getDefaultInstance().getContent();
          onChanged();
          return this;
        }
        void setContent(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000004;
          content_ = value;
          onChanged();
        }
        
        // @@protoc_insertion_point(builder_scope:google.protobuf.compiler.CodeGeneratorResponse.File)
      }
      
      static {
        defaultInstance = new File(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:google.protobuf.compiler.CodeGeneratorResponse.File)
    }
    
    private int bitField0_;
    // optional string error = 1;
    public static final int ERROR_FIELD_NUMBER = 1;
    private Object error_;
    public boolean hasError() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getError() {
      Object ref = error_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          error_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getErrorBytes() {
      Object ref = error_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        error_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .google.protobuf.compiler.CodeGeneratorResponse.File file = 15;
    public static final int FILE_FIELD_NUMBER = 15;
    private java.util.List<google.protobuf.compiler.Plugin.CodeGeneratorResponse.File> file_;
    public java.util.List<google.protobuf.compiler.Plugin.CodeGeneratorResponse.File> getFileList() {
      return file_;
    }
    public java.util.List<? extends google.protobuf.compiler.Plugin.CodeGeneratorResponse.FileOrBuilder> 
        getFileOrBuilderList() {
      return file_;
    }
    public int getFileCount() {
      return file_.size();
    }
    public google.protobuf.compiler.Plugin.CodeGeneratorResponse.File getFile(int index) {
      return file_.get(index);
    }
    public google.protobuf.compiler.Plugin.CodeGeneratorResponse.FileOrBuilder getFileOrBuilder(
        int index) {
      return file_.get(index);
    }
    
    private void initFields() {
      error_ = "";
      file_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getErrorBytes());
      }
      for (int i = 0; i < file_.size(); i++) {
        output.writeMessage(15, file_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getErrorBytes());
      }
      for (int i = 0; i < file_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(15, file_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static google.protobuf.compiler.Plugin.CodeGeneratorResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static google.protobuf.compiler.Plugin.CodeGeneratorResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static google.protobuf.compiler.Plugin.CodeGeneratorResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static google.protobuf.compiler.Plugin.CodeGeneratorResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static google.protobuf.compiler.Plugin.CodeGeneratorResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static google.protobuf.compiler.Plugin.CodeGeneratorResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static google.protobuf.compiler.Plugin.CodeGeneratorResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static google.protobuf.compiler.Plugin.CodeGeneratorResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static google.protobuf.compiler.Plugin.CodeGeneratorResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static google.protobuf.compiler.Plugin.CodeGeneratorResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(google.protobuf.compiler.Plugin.CodeGeneratorResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements google.protobuf.compiler.Plugin.CodeGeneratorResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return google.protobuf.compiler.Plugin.internal_static_google_protobuf_compiler_CodeGeneratorResponse_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return google.protobuf.compiler.Plugin.internal_static_google_protobuf_compiler_CodeGeneratorResponse_fieldAccessorTable;
      }
      
      // Construct using google.protobuf.compiler.Plugin.CodeGeneratorResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getFileFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        error_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (fileBuilder_ == null) {
          file_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          fileBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return google.protobuf.compiler.Plugin.CodeGeneratorResponse.getDescriptor();
      }
      
      public google.protobuf.compiler.Plugin.CodeGeneratorResponse getDefaultInstanceForType() {
        return google.protobuf.compiler.Plugin.CodeGeneratorResponse.getDefaultInstance();
      }
      
      public google.protobuf.compiler.Plugin.CodeGeneratorResponse build() {
        google.protobuf.compiler.Plugin.CodeGeneratorResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private google.protobuf.compiler.Plugin.CodeGeneratorResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        google.protobuf.compiler.Plugin.CodeGeneratorResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public google.protobuf.compiler.Plugin.CodeGeneratorResponse buildPartial() {
        google.protobuf.compiler.Plugin.CodeGeneratorResponse result = new google.protobuf.compiler.Plugin.CodeGeneratorResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.error_ = error_;
        if (fileBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            file_ = java.util.Collections.unmodifiableList(file_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.file_ = file_;
        } else {
          result.file_ = fileBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof google.protobuf.compiler.Plugin.CodeGeneratorResponse) {
          return mergeFrom((google.protobuf.compiler.Plugin.CodeGeneratorResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(google.protobuf.compiler.Plugin.CodeGeneratorResponse other) {
        if (other == google.protobuf.compiler.Plugin.CodeGeneratorResponse.getDefaultInstance()) return this;
        if (other.hasError()) {
          setError(other.getError());
        }
        if (fileBuilder_ == null) {
          if (!other.file_.isEmpty()) {
            if (file_.isEmpty()) {
              file_ = other.file_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureFileIsMutable();
              file_.addAll(other.file_);
            }
            onChanged();
          }
        } else {
          if (!other.file_.isEmpty()) {
            if (fileBuilder_.isEmpty()) {
              fileBuilder_.dispose();
              fileBuilder_ = null;
              file_ = other.file_;
              bitField0_ = (bitField0_ & ~0x00000002);
              fileBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getFileFieldBuilder() : null;
            } else {
              fileBuilder_.addAllMessages(other.file_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              error_ = input.readBytes();
              break;
            }
            case 122: {
              google.protobuf.compiler.Plugin.CodeGeneratorResponse.File.Builder subBuilder = google.protobuf.compiler.Plugin.CodeGeneratorResponse.File.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addFile(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string error = 1;
      private Object error_ = "";
      public boolean hasError() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getError() {
        Object ref = error_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          error_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setError(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        error_ = value;
        onChanged();
        return this;
      }
      public Builder clearError() {
        bitField0_ = (bitField0_ & ~0x00000001);
        error_ = getDefaultInstance().getError();
        onChanged();
        return this;
      }
      void setError(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        error_ = value;
        onChanged();
      }
      
      // repeated .google.protobuf.compiler.CodeGeneratorResponse.File file = 15;
      private java.util.List<google.protobuf.compiler.Plugin.CodeGeneratorResponse.File> file_ =
        java.util.Collections.emptyList();
      private void ensureFileIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          file_ = new java.util.ArrayList<google.protobuf.compiler.Plugin.CodeGeneratorResponse.File>(file_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          google.protobuf.compiler.Plugin.CodeGeneratorResponse.File, google.protobuf.compiler.Plugin.CodeGeneratorResponse.File.Builder, google.protobuf.compiler.Plugin.CodeGeneratorResponse.FileOrBuilder> fileBuilder_;
      
      public java.util.List<google.protobuf.compiler.Plugin.CodeGeneratorResponse.File> getFileList() {
        if (fileBuilder_ == null) {
          return java.util.Collections.unmodifiableList(file_);
        } else {
          return fileBuilder_.getMessageList();
        }
      }
      public int getFileCount() {
        if (fileBuilder_ == null) {
          return file_.size();
        } else {
          return fileBuilder_.getCount();
        }
      }
      public google.protobuf.compiler.Plugin.CodeGeneratorResponse.File getFile(int index) {
        if (fileBuilder_ == null) {
          return file_.get(index);
        } else {
          return fileBuilder_.getMessage(index);
        }
      }
      public Builder setFile(
          int index, google.protobuf.compiler.Plugin.CodeGeneratorResponse.File value) {
        if (fileBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFileIsMutable();
          file_.set(index, value);
          onChanged();
        } else {
          fileBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setFile(
          int index, google.protobuf.compiler.Plugin.CodeGeneratorResponse.File.Builder builderForValue) {
        if (fileBuilder_ == null) {
          ensureFileIsMutable();
          file_.set(index, builderForValue.build());
          onChanged();
        } else {
          fileBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addFile(google.protobuf.compiler.Plugin.CodeGeneratorResponse.File value) {
        if (fileBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFileIsMutable();
          file_.add(value);
          onChanged();
        } else {
          fileBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addFile(
          int index, google.protobuf.compiler.Plugin.CodeGeneratorResponse.File value) {
        if (fileBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFileIsMutable();
          file_.add(index, value);
          onChanged();
        } else {
          fileBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addFile(
          google.protobuf.compiler.Plugin.CodeGeneratorResponse.File.Builder builderForValue) {
        if (fileBuilder_ == null) {
          ensureFileIsMutable();
          file_.add(builderForValue.build());
          onChanged();
        } else {
          fileBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addFile(
          int index, google.protobuf.compiler.Plugin.CodeGeneratorResponse.File.Builder builderForValue) {
        if (fileBuilder_ == null) {
          ensureFileIsMutable();
          file_.add(index, builderForValue.build());
          onChanged();
        } else {
          fileBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllFile(
          Iterable<? extends google.protobuf.compiler.Plugin.CodeGeneratorResponse.File> values) {
        if (fileBuilder_ == null) {
          ensureFileIsMutable();
          super.addAll(values, file_);
          onChanged();
        } else {
          fileBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearFile() {
        if (fileBuilder_ == null) {
          file_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          fileBuilder_.clear();
        }
        return this;
      }
      public Builder removeFile(int index) {
        if (fileBuilder_ == null) {
          ensureFileIsMutable();
          file_.remove(index);
          onChanged();
        } else {
          fileBuilder_.remove(index);
        }
        return this;
      }
      public google.protobuf.compiler.Plugin.CodeGeneratorResponse.File.Builder getFileBuilder(
          int index) {
        return getFileFieldBuilder().getBuilder(index);
      }
      public google.protobuf.compiler.Plugin.CodeGeneratorResponse.FileOrBuilder getFileOrBuilder(
          int index) {
        if (fileBuilder_ == null) {
          return file_.get(index);  } else {
          return fileBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends google.protobuf.compiler.Plugin.CodeGeneratorResponse.FileOrBuilder> 
           getFileOrBuilderList() {
        if (fileBuilder_ != null) {
          return fileBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(file_);
        }
      }
      public google.protobuf.compiler.Plugin.CodeGeneratorResponse.File.Builder addFileBuilder() {
        return getFileFieldBuilder().addBuilder(
            google.protobuf.compiler.Plugin.CodeGeneratorResponse.File.getDefaultInstance());
      }
      public google.protobuf.compiler.Plugin.CodeGeneratorResponse.File.Builder addFileBuilder(
          int index) {
        return getFileFieldBuilder().addBuilder(
            index, google.protobuf.compiler.Plugin.CodeGeneratorResponse.File.getDefaultInstance());
      }
      public java.util.List<google.protobuf.compiler.Plugin.CodeGeneratorResponse.File.Builder> 
           getFileBuilderList() {
        return getFileFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          google.protobuf.compiler.Plugin.CodeGeneratorResponse.File, google.protobuf.compiler.Plugin.CodeGeneratorResponse.File.Builder, google.protobuf.compiler.Plugin.CodeGeneratorResponse.FileOrBuilder> 
          getFileFieldBuilder() {
        if (fileBuilder_ == null) {
          fileBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              google.protobuf.compiler.Plugin.CodeGeneratorResponse.File, google.protobuf.compiler.Plugin.CodeGeneratorResponse.File.Builder, google.protobuf.compiler.Plugin.CodeGeneratorResponse.FileOrBuilder>(
                  file_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          file_ = null;
        }
        return fileBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:google.protobuf.compiler.CodeGeneratorResponse)
    }
    
    static {
      defaultInstance = new CodeGeneratorResponse(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:google.protobuf.compiler.CodeGeneratorResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_compiler_CodeGeneratorRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_google_protobuf_compiler_CodeGeneratorRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_compiler_CodeGeneratorResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_google_protobuf_compiler_CodeGeneratorResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_compiler_CodeGeneratorResponse_File_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_google_protobuf_compiler_CodeGeneratorResponse_File_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n%google/protobuf/compiler/plugin.proto\022" +
      "\030google.protobuf.compiler\032 google/protob" +
      "uf/descriptor.proto\"}\n\024CodeGeneratorRequ" +
      "est\022\030\n\020file_to_generate\030\001 \003(\t\022\021\n\tparamet" +
      "er\030\002 \001(\t\0228\n\nproto_file\030\017 \003(\0132$.google.pr" +
      "otobuf.FileDescriptorProto\"\252\001\n\025CodeGener" +
      "atorResponse\022\r\n\005error\030\001 \001(\t\022B\n\004file\030\017 \003(" +
      "\01324.google.protobuf.compiler.CodeGenerat" +
      "orResponse.File\032>\n\004File\022\014\n\004name\030\001 \001(\t\022\027\n" +
      "\017insertion_point\030\002 \001(\t\022\017\n\007content\030\017 \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_google_protobuf_compiler_CodeGeneratorRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_google_protobuf_compiler_CodeGeneratorRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_google_protobuf_compiler_CodeGeneratorRequest_descriptor,
              new String[] { "FileToGenerate", "Parameter", "ProtoFile", },
              google.protobuf.compiler.Plugin.CodeGeneratorRequest.class,
              google.protobuf.compiler.Plugin.CodeGeneratorRequest.Builder.class);
          internal_static_google_protobuf_compiler_CodeGeneratorResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_google_protobuf_compiler_CodeGeneratorResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_google_protobuf_compiler_CodeGeneratorResponse_descriptor,
              new String[] { "Error", "File", },
              google.protobuf.compiler.Plugin.CodeGeneratorResponse.class,
              google.protobuf.compiler.Plugin.CodeGeneratorResponse.Builder.class);
          internal_static_google_protobuf_compiler_CodeGeneratorResponse_File_descriptor =
            internal_static_google_protobuf_compiler_CodeGeneratorResponse_descriptor.getNestedTypes().get(0);
          internal_static_google_protobuf_compiler_CodeGeneratorResponse_File_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_google_protobuf_compiler_CodeGeneratorResponse_File_descriptor,
              new String[] { "Name", "InsertionPoint", "Content", },
              google.protobuf.compiler.Plugin.CodeGeneratorResponse.File.class,
              google.protobuf.compiler.Plugin.CodeGeneratorResponse.File.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
